###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: vipa-memcached

    postgres:
      image: postgres:9.6-alpine
      container_name: vipa-postgres
      working_dir: /var/www
      environment:
        - POSTGRES_USER=vipa
        - POSTGRES_PASSWORD=vipa
        - POSTGRES_DB=vipa

    elasticsearch:
      image: elasticsearch:1.7-alpine
      container_name: vipa-elasticsearch

    webserver:
      image: nginx:alpine
      container_name: vipa-webserver
      working_dir: /var/www
      volumes:
          - ./var/www/:/var/www
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/sites-available/vipa
      ports:
          - "8083:80"
      links:
          - php-fpm
      depends_on: 
          - php-fpm

    php-fpm:
      build:
        context: .
        dockerfile: phpdocker/php-fpm/Dockerfile
      container_name: vipa-php-fpm
      working_dir: /var/www
      command: "su -s /bin/bash www-data \ 
                && cd /var/www/vipa \
                && php app/console assets:install web --symlink \
                && php app/console assetic:dump  \
                && php app/console doctrine:schema:drop --force  \
                && php app/console doctrine:schema:create  \
                && php app/console vipa:install  \
                && php app/console vipa:install:samples  \
                && php app/console vipa:install:initial-data"
      volumes:
        - ./var/www/:/var/www
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini
      depends_on: 
        - memcached
        - postgres
        - elasticsearch
      links:
        - memcached
        - postgres
        - elasticsearch
